name: Run Playwright Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      vaadin-app:
        image: docker.io/library/openjdk:17-jdk-slim
        ports:
          - 8080:8080
        options: >-
          --health-cmd "curl --fail http://localhost:8080 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - .:/usr/src/app
        working_dir: /usr/src/app
        command: bash -c "git clone https://github.com/olucasporto/vaadin-starter-proj.git && cd vaadin-starter-proj && ./mvnw clean install && ./mvnw spring-boot:run"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Run Playwright Tests
      run: npx playwright test
      env:
        CI: true

