name: Run Playwright Tests for Vaadin

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt' # Instala o AdoptOpenJDK
          java-version: '17'

      - name: Build Vaadin project
        run: |
          git clone https://github.com/olucasporto/vaadin-starter-proj.git
          cd vaadin-starter-proj
          ./mvnw clean install

      - name: Run Vaadin App
        run: |
          cd vaadin-starter-proj
          ./mvnw spring-boot:run &
          sleep 60 # Aguarda o servidor subir

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps # Instala os navegadores necessários

      - name: Compile TypeScript
        run: tsc

      - name: Run Playwright Tests
        run: npx playwright test
        env:
          CI: true
